version: '3.1'

services:
  simple-contact-list:
    image: simple-contact-list
    build: .
    ports:
      - 8080:8080
  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: go_training_contactList
    ports:
      - 3306:3306
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-vue
# # Do I need to do that?
# volumes:
#   db_data: