
# golang:onbuild automatically copies the package source, 
# fetches the application dependencies, builds the program, 
# and configures it to run on startup 
FROM golang:1.9.2-alpine3.6

LABEL Name=simple-contact-list Version=0.0.1 



EXPOSE 8080

# For more control, you can copy and build manually
# FROM golang:latest 
# LABEL Name=simple-contact-list Version=0.0.1 
# RUN mkdir /app 
# ADD . /app/ 
# WORKDIR /app 
# RUN go build -o main .
# EXPOSE 8080 
# CMD ["/app/main"]
